baseURL = "https://www.varnalabs.in"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "VarnaLabs"
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 4
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5
[params]
address = "Hyderabad | Rishikesh | Delhi"
author = "Aditya Kesanupalli"
copyright = "Copyright &copy; 2020 a website by [Varnalabs](https://www.varnalabs.in)"
description = "Varnalabs Creative Design Agency"
email = "aditya@varnalabs.in"
google_analytics_id = ""
home = "Home"
logo = "images/logo.png"
phone = "+91 9176 333 857"
theme_color = "#41228e"
[params.contact]
enable = true
form_action = "#"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
URL = "www.facebook.com/varnalabs"
icon = "ti-facebook"
[[params.social]]
URL = "www.instagram.com/varnalabs"
icon = "ti-instagram"
[[params.social]]
URL = "www.twitter.com/varnalabs"
icon = "ti-twitter-alt"
[[params.social]]
URL = "www.linkedin.com/varnalabs"
icon = "ti-linkedin"
